---
- name: Create namespace
  ansible.builtin.import_tasks: create_ns.yml

- name: ConfigMap 
  ansible.builtin.import_tasks: configmap.yml 

- name: Secrets 
  ansible.builtin.import_tasks: secret.yml

- name: Servics
  ansible.builtin.import_tasks: services.yml

- name: Deploy wazuh
  ansible.builtin.import_tasks: wazuh.yml