---
- name: Deploy dashboard-cred
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/dashboard-cred-secret.yml.j2
    apply: true
  tags: dashboard-cred

- name: Deploy indexer-cred
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/indexer-cred-secret.yml.j2
    apply: true
  tags: indexer-cred

- name: Deploy wazuh-api-cred
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/wazuh-api-cred-secret.yml.j2
    apply: true
  tags: wazuh-api-cred

- name: Deploy wazuh-authd-pass
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/wazuh-authd-pass-secret.yml.j2
    apply: true
  tags: authd-pass

- name: Deploy wazuh-cluster-key
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/wazuh-cluster-key-secret.yml.j2
    apply: true
  tags: cluster-key

# For testing only !!!!!
- name: Deploy dashboard cert
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: dashboard-certs
        namespace: wazuh
      type: Opaque
      data:
          cert.pem: "{{ lookup('file', 'test/dashboard_http/cert.pem') | b64encode }}"
          key.pem: "{{ lookup('file', 'test/dashboard_http/key.pem') | b64encode }}"
          root-ca.pem: "{{ lookup('file', 'test/indexer_cluster/root-ca.pem') | b64encode }}"
  tags: dashboard

- name: Deploy indexer cert
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: indexer-certs
        namespace: wazuh
      type: Opaque
      data:
        root-ca.pem: "{{ lookup('file', 'test/indexer_cluster/root-ca.pem') | b64encode }}"
        node.pem: "{{ lookup('file', 'test/indexer_cluster/node.pem') | b64encode }}"
        node-key.pem: "{{ lookup('file', 'test/indexer_cluster/node-key.pem') | b64encode }}"
        dashboard.pem: "{{ lookup('file', 'test/indexer_cluster/dashboard.pem') | b64encode }}"
        dashboard-key.pem: "{{ lookup('file', 'test/indexer_cluster/dashboard-key.pem') | b64encode }}"
        admin.pem: "{{ lookup('file', 'test/indexer_cluster/admin.pem') | b64encode }}"
        admin-key.pem: "{{ lookup('file', 'test/indexer_cluster/admin-key.pem') | b64encode }}"
        filebeat.pem: "{{ lookup('file', 'test/indexer_cluster/filebeat.pem') | b64encode }}"
        filebeat-key.pem: "{{ lookup('file', 'test/indexer_cluster/filebeat-key.pem') | b64encode }}"