---
- name: Deploy dashboard-cred
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/dashboard-cred-secret.yml.j2
    apply: true
  tags: dashboard-cred

- name: Deploy indexer-cred
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/indexer-cred-secret.yml.j2
    apply: true
  tags: indexer-cred

- name: Deploy wazuh-api-cred
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/wazuh-api-cred-secret.yml.j2
    apply: true
  tags: wazuh-api-cred

- name: Deploy wazuh-authd-pass
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/wazuh-authd-pass-secret.yml.j2
    apply: true
  tags: authd-pass

- name: Deploy wazuh-cluster-key
  kubernetes.core.k8s:
    state: present
    namespace: wazuh
    template: wazuh/secrets/wazuh-cluster-key-secret.yml.j2
    apply: true
  tags: cluster-key

